services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: pantrypal
      POSTGRES_PASSWORD: pantrypal
      POSTGRES_DB: pantrypal
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
