"""add counts table

Revision ID: 604f500d0e91
Revises: bf3a813db37e
Create Date: 2025-10-16 21:04:15.787235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '604f500d0e91'
down_revision: Union[str, Sequence[str], None] = 'bf3a813db37e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('counts', sa.Column('notes', sa.Text(), nullable=True))
    op.drop_column('counts', 'last_updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('counts', sa.Column('last_updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('counts', 'notes')
    # ### end Alembic commands ###
